[webservers]
target ansible_host=127.0.0.1 ansible_port=2222 ansible_user=ansible ansible_ssh_pass=ansible ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
